export const jobTitles = [
  'Software Engineer',
  'Software Developer',
  'Full Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'DevOps Engineer',
  'Data Scientist',
  'Machine Learning Engineer',
  'Product Manager',
  'Project Manager',
  'UI/UX Designer',
  'Web Developer',
  'Mobile Developer',
  'iOS Developer',
  'Android Developer',
  'Cloud Engineer',
  'Systems Administrator',
  'Database Administrator',
  'Quality Assurance Engineer',
  'Security Engineer',
  'Network Engineer',
  'Business Analyst',
  'Data Analyst',
  'Technical Writer',
  'Scrum Master',
  'IT Support Specialist',
  'Technical Support Engineer',
  'Solutions Architect',
  'Cloud Architect',
  'Engineering Manager',
].map((title, index) => ({
  id: index.toString(),
  text: title
})) 